FROM golang:1.19-bullseye AS builder
RUN go version && apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -qq -y install upx-ucl

ARG component

ADD . /gobuild
WORKDIR /gobuild
RUN make verify-deps static
RUN apt-get -yq purge upx-ucl
RUN mv /gobuild/${component} /
WORKDIR /
RUN rm -rf /gobuild
FROM gcr.io/distroless/static
COPY --from=builder /node-role-labeler /
ENTRYPOINT ["/node-role-labeler"]
